[package]
name = "generativity-pattern-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
generativity = "1.1.0"

[dev-dependencies]
criterion = "0.6"

[[bench]]
name = "my_benchmark"
harness = false
